### ISSUE TITLE
换了lfw数据后运行报错

### ISSUE THREAD

**Issue by chenyuqing** [MrZhousf/tf_facenet#3]
利用自己爬取的图片来做评估,做了detect & align, 然后运行create_eval_data.py, 报以下错误.

Saving variables
Variables saved in 0.27 seconds
Saving metagraph
Metagraph saved in 1.84 seconds
Running forward pass on LFW images: Traceback (most recent call last):
  File "/home/ares2/workspace/tf_facenet/facenet-master/src/train_tripletloss.py", line 487, in <module>
    main(parse_arguments(sys.argv[1:]))
  File "/home/ares2/workspace/tf_facenet/facenet-master/src/train_tripletloss.py", line 196, in main
    args.lfw_nrof_folds, log_dir, step, summary_writer, args.embedding_size)
  File "/home/ares2/workspace/tf_facenet/facenet-master/src/train_tripletloss.py", line 351, in evaluate
    labels_array = np.reshape(np.arange(nrof_images),(-1,3))
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 292, in reshape
    return _wrapfunc(a, 'reshape', newshape, order=order)
  File "/usr/local/lib/python3.5/dist-packages/numpy/core/fromnumeric.py", line 56, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: cannot reshape array of size 185600 into shape (3)

**Comment by chenyuqing** [comment]
运行train.py报的错误
